val hudiDf = spark.read.format("org.apache.hudi").load("/tmp/hudi-deltastreamer-ny/")
val inputDf = spark.read.format("parquet").load("/opt/bundle-validation/data/utilities/parquet_src")
hudiDf.registerTempTable("hudi_tbl")
inputDf.registerTempTable("src_tbl")
val hudiCount = spark.sql("select distinct date_col, VendorID from hudi_tbl").count()
val srcCount = spark.sql("select distinct date_col, VendorID from src_tbl").count()
if (hudiCount == srcCount) System.exit(0)
println(s"Counts don't match hudiCount: $hudiCount, srcCount: $srcCount")
System.exit(1)
