hoodie.datasource.write.recordkey.field=key
hoodie.datasource.write.partitionpath.field=date
hoodie.datasource.write.precombine.field=ts
hoodie.metadata.enable=true
hoodie.deltastreamer.source.dfs.root=file:///opt/bundle-validation/utilities/stocks/data
hoodie.deltastreamer.schemaprovider.target.schema.file=file:///opt/bundle-validation/utilities/stocks/schema.avsc
hoodie.deltastreamer.schemaprovider.source.schema.file=file:///opt/bundle-validation/utilities/stocks/schema.avsc
